apiVersion: apps/v1
kind: Deployment
metadata:
  name: java_web
spec:
  selector:
    matchLabels:
      app: java_web
  replicas: 2
  template:
    metadata:
      labels:
        app: java_web
    spec:
      containers:
      - name: java_web
        image: rajanup77/java_web:latest
        ports:
        - containerPort: 8080

