apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaweb
spec:
  selector:
    matchLabels:
      app: javaweb-deploy
  replicas: 2
  template:
    metadata:
      labels:
        app: javaweb-app
    spec:
      containers:
      - name: javaweb
        image: rajanup77/java_web:latest
        ports:
        - containerPort: 8080

