apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: argocd
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: rajanup77/amd-nginx
        ports:
        - containerPort: 8080

