apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappDeployment
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: yeasy/simple-web
        ports:
        - containerPort: 8080

