apiVersion: v1
kind: Service
metadata:
  name: webappsvc
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32000
